<a href="https://colab.research.google.com/github/palash116/FirstCode2025/blob/week_5/HW_week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Load the dataset**

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
from google.colab import drive
drive.mount('/content/drive')
import warnings
warnings.filterwarnings('ignore')

Mounted at /content/drive

In [3]:
df = pd.read_csv('/content/drive/MyDrive/datasets/Housing.csv')

In [4]:
display(df)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

# How many houses are there?

In [5]:
print("Number of houses:",df.shape[0])

Number of houses: 545

# Show first 3 houses

In [6]:
print('\nFirst 3 houses:')
df.head(3)

First 3 houses:

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished

# Show all column names

In [7]:
print("Columns:")
print(df.columns.tolist())

Columns:
['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea', 'furnishingstatus']

# Show data types of columns

In [8]:
print("Data types of columns:")
print(df.dtypes)

Data types of columns:
price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

# Convert Yes/No to 1/0

In [20]:
print("\n Current mainroad values:" )
print(df['mainroad'].head(5))

 Current mainroad values:
0    yes
1    yes
2    yes
3    yes
4    yes
Name: mainroad, dtype: object

In [31]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['mainroad_encoded'] = label_encoder.fit_transform(df['mainroad'])
print("\nAfter Label Encoding of mainroad:")
print(df[['mainroad','mainroad_encoded']])

After Label Encoding of mainroad:
    mainroad  mainroad_encoded
0        yes                 1
1        yes                 1
2        yes                 1
3        yes                 1
4        yes                 1
..       ...               ...
540      yes                 1
541       no                 0
542      yes                 1
543       no                 0
544      yes                 1

[545 rows x 2 columns]

# Create new data set by encoding catagorical value for analysis

In [85]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
data=pd.DataFrame()
data['price']=df['price']
data['area']=df['area']
data['bedroomes']=df['bedrooms']
data['bathrooms']=df['bathrooms']
data['stories']=df['stories']
data['price']=df['price']
label_encoder = LabelEncoder()
data['mainroad_encoded'] = label_encoder.fit_transform(df['mainroad'])
data['guestroom_encoded'] = label_encoder.fit_transform(df['guestroom'])
data['basement_encoded'] = label_encoder.fit_transform(df['basement'])
data['hotwaterheating_encoded'] = label_encoder.fit_transform(df['hotwaterheating'])
data['airconditioning_encoded'] = label_encoder.fit_transform(df['airconditioning'])
data['parking']=df['parking']
data['prefarea_encoded'] = label_encoder.fit_transform(df['prefarea'])
data['furnishingstatus_encoded'] = label_encoder.fit_transform(df['furnishingstatus'])

In [86]:
display(data)

,price,area,bedroomes,bathrooms,stories,mainroad_encoded,guestroom_encoded,basement_encoded,hotwaterheating_encoded,airconditioning_encoded,parking,prefarea_encoded,furnishingstatus_encoded
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,2
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,2
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,2

# Split into Train and Test

In [87]:
X=data.drop('price',axis=1)
y=data['price']
# Split: 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,    # 20% for test
    random_state=20   # Same result every time
)

print(f"\nWe will train with: {len(X_train)} houses")
print(f"We will test with: {len(X_test)} houses")

We will train with: 436 houses
We will test with: 109 houses

In [88]:
display(X_train)

,area,bedroomes,bathrooms,stories,mainroad_encoded,guestroom_encoded,basement_encoded,hotwaterheating_encoded,airconditioning_encoded,parking,prefarea_encoded,furnishingstatus_encoded
370,4280,2,1,1,1,0,0,0,1,2,0,1
438,4500,2,1,1,0,0,0,0,0,0,0,1
528,3970,1,1,1,0,0,0,0,0,0,0,2
119,7020,3,1,1,1,0,1,0,1,2,1,1
7,16200,5,3,2,1,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
218,4815,2,1,1,1,0,0,0,1,0,1,1
223,6321,3,1,2,1,0,1,0,1,1,0,0
271,1905,5,1,2,0,0,1,0,0,0,0,1
474,4352,4,1,2,0,0,0,0,0,1,0,2
355,8250,3,1,1,1,0,0,0,0,2,0,0

In [89]:
display(X_test)

,area,bedroomes,bathrooms,stories,mainroad_encoded,guestroom_encoded,basement_encoded,hotwaterheating_encoded,airconditioning_encoded,parking,prefarea_encoded,furnishingstatus_encoded
56,11440,4,1,2,1,0,1,0,0,1,1,1
290,2610,4,3,2,0,0,0,0,0,0,0,1
16,6600,4,2,2,1,1,1,0,1,1,1,2
410,3850,3,1,1,1,0,0,0,0,0,0,2
129,11460,3,1,3,1,0,0,0,0,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
433,3480,4,1,2,0,0,0,0,0,1,0,1
365,5450,2,1,1,1,0,0,0,0,0,0,0
383,4500,4,2,2,1,0,1,0,0,2,0,0
145,5000,3,1,4,1,0,0,0,0,0,0,0
197,2800,3,2,2,0,0,1,0,1,1,0,1

# Apply StandardScaler

In [90]:
print(f"Area: smallest={X_train['area'].min()}, biggest={X_train['area'].max()}")

Area: smallest=1650, biggest=16200

In [91]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("\nAfter scaling:")
print("All features now have similar range!")
print(f"Example - First House's area before scaling: {X_train.values[1][0]}")
print(f"Example - First House's area after scaling: {X_train_scaled[1][0]:.2f}")

After scaling:
All features now have similar range!
Example - First House's area before scaling: 4500
Example - First House's area after scaling: -0.30

# train and test model

In [95]:
from sklearn.linear_model import LogisticRegression

# Create model
model = LogisticRegression(max_iter=1000)

# Train the model
model.fit(X_train_scaled, y_train)
print("✅ Model trained!")

y_pred = model.predict(X_test_scaled)
comparison = pd.DataFrame({
    "Actual Price": y_test.values[:5],
    "Predicted Price": y_pred[:5]
})
display(comparison)

✅ Model trained!

   Actual Price  Predicted Price
0       7343000          5600000
1       4200000          2660000
2       9100000          5250000
3       3430000          2660000
4       5873000          5600000

# Predict a House Price

In [107]:
new_house = pd.DataFrame([{
    'area': 5000,
    'bedrooms': 3,
    'bathrooms': 2,
    'stories': 2,
    'mainroad': 1,
    'guestroom': 0,
    'basement': 1,
    'hotwaterheating': 0,
    'airconditioning': 1,
    'parking': 2,
    'prefarea': 1,
    'furnishingstatus': 0
}])
predicted_price = model.predict(new_house)[0]   # [0] means the result will be shown without []
print("\nPredicted House Price:", predicted_price)

Predicted House Price: 5943000